name: release-version
author: gendloop
description: 'release-version'
inputs:
  version:
    description: 'New Version'
    required: true
    default: '0.0.0'

runs:
  using: 'composite'
  steps:
    - name: test
      run: |
        echo ${{ github.action_path }}
        echo ${{ github.action_repository }}
        echo ${{ github.repository }}