name: Release_Version

permissions:
  contents: write
  actions: write

on: 
  push:
    tags:
      - 'v*'

jobs:
  release_version:
    runs-on: windows-latest
    steps:
      uses: gendloop/release-version@v1.0.0
      with:
        version: ${{ github.ref_name }}
          
      
        
        