name: Release_Version

permissions:
  contents: write
  actions: write

on: 
  push:
    tags:
      - 'v*'

jobs:
  release_version:
    runs-on: windows-latest
    steps:
      - name: releaes-version
        uses: gendloop/release-version@main
        with:
          repo: ${{ github.repository }}
          version: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

          
      
        
        